site_name: Jewish Music Wiki
theme:
  name: material
  features:
    - navigation.tabs
    - search.suggest
    - content.action.edit
repo_url: https://github.com/espire/jewishmusic
edit_uri: edit/main/docs/
